language: python
python:
    - "2.6"
    - "2.7"
env:
  - TOX_ENV=ci14
  - TOX_ENV=ci15

install:
    - pip install tox --use-mirrors
script:
    tox -e $TOX_ENV
notifications:
    email:
        recipients:
          - github@spalletti.it
        on_success: never
        on_failure: always