language: python

python:
    - 2.6
    - 2.7

env:
    - TOX_ENV=dj14
    - TOX_ENV=dj15
    - TOX_ENV=dj16
    - TOX_ENV=cms23
    - TOX_ENV=cms24_14

install:
    - pip install tox
    - pip install python-coveralls coverage

script:
    - tox -e $TOX_ENV

after_success:
    - coveralls --config_file=coverage.rc

matrix:
    allow_failures:
        - TOX_ENV=dj16

notifications:
    email:
        recipients:
          - github@spalletti.it
        on_success: never
        on_failure: always
